<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ho_template"
 *
 * Auto generated by Extension Builder 2019-01-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Plugin du template du site',
    'description' => 'Template qui définit la structure générale du site',
    'category' => 'templates',
    'author' => 'TABARY Olivier',
    'author_email' => 'olivier.tabary@wanadoo.fr',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
